name: CICD-ICARE-NODEJS

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
      - name: Install dependencies
        run: npm install

      - name: build docker image
        run: docker image build -t ${{ secrets.DOCKER_USERNAME }}/icarenodejs:1.0 .
      
      - name: run container
        run: docker container run -d -p 3000:3000 --name icarecontainer icarenodejs:1.0

      - name: login to dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}"  --password-stdin

      - name: push image to dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/icarenodejs:1.0

      - name: done
        run: echo "image pushed to dockerhub!"

